export const SET_MOVIES ='SET_MOVIES';
export const SEARCH_INPUT_VALUE ='SEARCH_INPUT_VALUE';
export const SET_MOVIES_FAVORITE ='SET_MOVIES_FAVORITE';
export const LOGGED_IN_USER ='LOGGED_IN_USER';
export const LOGOUT ='LOGGED_IN_USER';
